# Generated by Django 3.2.7 on 2021-09-12 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0002_auto_20210912_1945'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newuser',
            name='is_staff',
        ),
    ]
