# Generated by Django 3.2.7 on 2021-09-12 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0006_managerassigned'),
    ]

    operations = [
        migrations.RenameField(
            model_name='managerassigned',
            old_name='assigned_by',
            new_name='manager',
        ),
        migrations.RenameField(
            model_name='managerassigned',
            old_name='assigned_to',
            new_name='user',
        ),
    ]
