# Generated by Django 3.2.7 on 2021-09-12 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0007_auto_20210912_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='username',
            field=models.CharField(max_length=70, null=True, unique=True),
        ),
    ]
