# Generated by Django 3.2.7 on 2021-09-12 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0010_alter_managerassigned_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='role',
            field=models.CharField(default='user', max_length=30),
        ),
    ]
