# Generated by Django 3.2.7 on 2021-09-12 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0011_alter_newuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='password',
            field=models.CharField(max_length=255),
        ),
    ]
