# Generated by Django 3.2.7 on 2021-09-12 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0001_initial'),
        ('todoapp', '0012_alter_newuser_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='managerassigned',
            name='task_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task', to='taskapp.task'),
        ),
    ]
