# Generated by Django 3.2.7 on 2021-09-12 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0002_auto_20210913_0036'),
        ('todoapp', '0013_managerassigned_task_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='managerassigned',
            name='task_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task', to='taskapp.task'),
        ),
    ]
